application:

  # 输入配置 - 定义规则源
  input:
    - name: 'AWAvenue-Ads-Rule'
      path: 'https://github.boki.moe/https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/AWAvenue-Ads-Rule.txt'
      type: easylist

    - name: 'DD-AD'
      path: 'https://gcore.jsdelivr.net/gh/afwfv/DD-AD@refs/heads/release/DD-AD.txt'
      type: easylist

    - name: 'adblockdns'
      path: 'https://gcore.jsdelivr.net/gh/217heidai/adblockfilters@main/rules/adblockdns.txt'
      type: easylist

  # 输出配置
  output:
    # 文件头配置，将自动作为注释添加至每个规则文件开始
    # 可使用占位符 ${name}、${type}、${desc} 以及 ${date} (当前日期)、${total} (规则总数)
    file_header: |
      ADFS AdBlock ${type}
      Last Modified: ${date}
      Total Size: ${total}
      Homepage: https://github.com/fordes123/ad-filters-subscriber/
      
    files:
      - name: clash.yaml
        type: clash
        desc: 'Merged AdBlock Rules for Clash'
        filter:
          - basic
          - wildcard
          - unknown

  # 程序运行配置（可选）
  config:
    # 解析器配置
    parser:
      # 预期总规则数量，有助于提前分配内存以提高去重性能
      expected: 300000
